### ISSUE TITLE
关于损失函数

### ISSUE THREAD

**Issue by HeSasa** [winycg/MCL#2]
![111](https://user-images.githubusercontent.com/32067974/204342197-085b58be-d590-4459-93ef-b707190baf5c.png)
![222](https://user-images.githubusercontent.com/32067974/204342209-16db0244-4988-4d25-a745-005695d0907f.png)
想请问这里为什么是1  而不是k？

**Comment by winycg** [comment]
Hi，p_m^k表示p_m分布的第k个元素，是一种表示形式。p^1_m表示第一个元素，代表anchor样本与正样本的基于similarity的概率值。基于InfoNCE的误差函数则是对于anchor样本与正样本概率值的负对数似然（即交叉熵误差）。

**Comment by HeSasa** [comment]
理解了，非常感谢！
